### PR TITLE
WIP: Fix prefixes for posts

### LINKED ISSUE #256: Prefixes can not be found in posts
MWE #257

### PR DESCRIPTION
**Pull request by Simaris**
Fix #256, Close #257 
- [x] Create MWE gem theme (or test equivalent)
- [x] Create MWE test for not failing if an undefined layout is specified for a page

### CODE REVIEW

File: lib/jekyll/helper/rdf_hook_helper.rb [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+        def backload_prefixes page, payload
+          prefix_path = page.data["rdf_prefix_path"]
+          # posts frontmatter does not contain values from layout frontmatters
+          if(prefix_path.nil?)
+            unless(payload.layout.nil? || page.data["layout"].nil?)
+              prefix_path = payload.layout["rdf_prefix_path"]
+              base_path = search_prefix_definition page.site.layouts[page.data["layout"]], prefix_path
+            end
+          else
+            base_path = payload.site["source"]#page.path[0..-(page.relative_path.length + 1)]
```
Comment (white-gecko) [inline lib/jekyll/helper/rdf_hook_helper.rb]: please remove out commented part
